// ===========================
// CONTEXTO: IDIOMA
// ===========================

import React, { createContext, useContext, useEffect, useState } from 'react';
import { loadSettings, saveSettings } from '../utils/storage';

export type LangType = 'pt' | 'en' | 'es';

// ===========================
// TRADUÇÕES
// ===========================
const translations = {
  pt: {
    nav: {
      eventos: 'Eventos',
      calendario: 'Calendário',
      listas: 'Listas',
      pendencias: 'Pendências',
      config: 'Config',
    },
    common: {
      save: 'Salvar',
      cancel: 'Cancelar',
      edit: 'Editar',
      delete: 'Excluir',
      back: '← Voltar',
      confirm: 'Confirmar',
      allDay: 'Dia Todo',
      create: 'Criar',
      share: 'Compartilhar',
      archive: 'Arquivar',
      link: 'Vincular Lista',
      linkShort: 'Vincular',
      unlink: 'Desvincular',
      complete: 'Concluir',
      reopen: 'Reabrir',
      suspend: 'Suspender',
      resume: 'Retomar',
      postpone: 'Adiar',
      schedule: 'Agendar',
      note: 'Anotar',
      viewList: 'Ver lista',
      done: 'Concluído',
      pending: 'PENDENTE',
      late: 'ATRASADO',
      suspended: 'SUSPENSA',
      suspendedBadge: 'SUSPENSO',
      completed: 'Concluída',
      open: 'Em aberto',
      today: 'Hoje',
      notes: 'Anotações',
      notesPlaceholder: 'Escreva uma anotação...',
      linkedList: 'Lista vinculada',
      exit: 'Sair',
      unshare: 'Descompartilhar',
      finalize: 'Finalizar',
      pendingLabel: 'Pendente',
      error: 'Erro',
      detailPending: 'Pendência',
      detailEvent: 'Compromisso',
      detailRotina: 'Rotina',
    },
    home: {
      noEvents: 'Nenhum compromisso hoje',
      sectionEvents: 'COMPROMISSOS DE HOJE',
      sectionRoutines: 'MINHAS ROTINAS DE HOJE',
      sectionRoutinesOtherDay: 'MINHAS ROTINAS NESTE DIA',
      sectionToday: 'MEUS EVENTOS DE HOJE',
      sectionTodayOtherDay: 'MEUS EVENTOS NESTE DIA',
      sectionAppointments: 'MEUS COMPROMISSOS DE HOJE',
      sectionAppointmentsOtherDay: 'MEUS COMPROMISSOS NESTE DIA',
      createBtn: 'Novo Evento',
      emptyTitle: 'Tudo em paz!',
      emptySubtitle: 'Nenhum evento hoje.',
      subtitle: (events: number, completed: number) =>
        `${events} evento${events !== 1 ? 's' : ''} hoje . ${completed} concluído${completed !== 1 ? 's' : ''}`,
      allDone: 'Tudo concluído hoje',
      // Vista alternativa
      altMyRoutines: 'Rotinas',
      altMyAppointments: 'Compromissos',
      altOf: 'de',
      altCompleted: 'concluída',
      altCompletedPlural: 'concluídas',
      altActive: 'ativa',
      altActivePlural: 'ativas',
      altActiveAppointment: 'ativo',
      altActiveAppointmentPlural: 'ativos',
      altCompletedAppointment: 'concluído',
      altCompletedAppointmentPlural: 'concluídos',
      altRoutinesSubtitle: (active: number, completed: number) =>
        `${active} ativa${active !== 1 ? 's' : ''} . ${completed} concluída${completed !== 1 ? 's' : ''}`,
      altAppointmentsSubtitle: (active: number, completed: number) =>
        `${active} ativo${active !== 1 ? 's' : ''} . ${completed} concluído${completed !== 1 ? 's' : ''}`,
      altBack: 'Voltar',
      // Animação overview
      greetingHello: (name: string) => `Olá ${name},`,
      mantra: 'Tudo em paz!',
      allDoneSubtitle: 'Nenhum evento em aberto',
      emptyDaySubtitle: 'Nenhum compromisso agendado',
      todayYouHave: 'Hoje você tem:',
      thisDayYouHave: 'Neste dia você tem:',
      bodyTitle: 'Meus eventos:',
      myRoutinesLabel: 'Rotinas',
      myAppointmentsLabel: 'Compromissos',
      viewBtn: 'Ver',
    },
    lists: {
      title: 'supLista',
      createBtn: 'Criar nova lista',
      sectionOpen: 'MEU PROGRESSO:',
      sectionDone: 'CONCLUÍDAS / ARQUIVADAS',
      createTitle: 'Criar Lista',
      createSubtitle: 'Preencha os detalhes da lista',
      fieldTitle: 'Título',
      tagLabel: 'Tag',
      typeLabel: 'Tipo de Lista',
      typeShopping: '🛒 Compras',
      typeTasks: '📋 Tarefas',
      shoppingLabel: 'Compras',
      tasksLabel: 'Tarefas',
      itemsSection: 'ITENS',
      itemsBtn: 'Itens',
      nameLabel: 'Nome da Lista *',
      placeholderShopping: 'Ex: Mercado, Padaria...',
      placeholderTasks: 'Ex: Limpeza, Rotina...',
      inheritLabel: 'Herdar de lista anterior (opcional)',
      inheritSelect: '+ Selecionar lista para herdar',
      inheritModalTitle: 'Herdar de lista anterior',
      addItem: 'Adicionar Item',
      addTask: 'Adicionar Tarefa',
      finalize: 'Finalizar',
      noItems: 'Nenhum item ainda.\nToque em "Adicionar Item" abaixo.',
      subtitle: (total: number, closed: number) =>
        `${total} lista${total !== 1 ? 's' : ''} . ${closed} concluída${closed !== 1 ? 's' : ''}`,
      linkedTo: 'Vinculada:',
      linkModalTitle: 'Vincular a Evento ou Pendência',
      linkModalEmpty: 'Nenhum evento ou pendência disponível.',
      linkTypePending: 'Pendência',
      linkTypeEvent: 'Evento',
      noneYet: 'Nenhum item ainda',
      bodyTitle: 'Minhas listas:',
      greetingSubtitle: 'Estas são suas listas:',
      mantra: 'Tudo certo!',
      emptyTitle: 'Tudo certo!',
      emptySubtitle: 'Nenhuma lista ainda.',
      allDoneTitle: 'Tudo certo!',
      allDoneSubtitle: 'Nenhuma lista em aberto',
    },
    shoppingItem: {
      placeholderShopping: 'Ex: Arroz, Feijão...',
      placeholderTask: 'Ex: Lavar louça, Varrer...',
      qtyLabel: 'Qtd:',
      unitLabel: 'Unidade:',
      unitPickerTitle: 'Selecionar Unidade',
      errorRequired: 'Nome do item é obrigatório',
      priceErrorRequired: 'Digite um preço válido',
      priceLabel: 'Preço (R$):',
      addPrice: 'Adicionar Preço',
      pricePerUnit: 'Por unidade',
      priceTotal: 'Preço total',
      editItem: 'Editar Item',
      editTask: 'Editar Tarefa',
    },
    units: {
      unidade: 'Unidade',
      kg: 'Kg',
      g: 'g',
      litros: 'Litros',
      ml: 'ml',
      mt: 'mt',
      cm: 'cm',
      porção: 'Porção',
      pedaço: 'Pedaço',
    },
    tags: {
      Trabalho: 'Trabalho',
      Pessoal: 'Pessoal',
      Saúde: 'Saúde',
      Família: 'Família',
      Financeiro: 'Financeiro',
      Estudos: 'Estudos',
      Lazer: 'Lazer',
      Outro: 'Outro',
      Geral: 'Geral',
      Personalizar: 'Personalizar',
      customTagPlaceholder: 'Digite sua tag...',
    },
    settings: {
      title: 'Configurações',
      subtitle: 'Seus ajustes e preferências',
      // Menu principal
      menuProfile: 'Meu Perfil',
      menuProfileSubtitle: 'Nome e conta',
      menuOptions: 'Preferências',
      menuOptionsSubtitle: 'Tema e idioma',
      menuNotifications: 'Notificações',
      menuNotificationsSubtitle: 'Alertas de eventos, listas, pendências e hidratação',
      menuSpecialFeatures: 'Recursos Especiais',
      menuSpecialFeaturesSubtitle: 'Hidratação e outros recursos extras',
      menuWater: 'Contador de Hidratação',
      menuWaterSubtitle: 'Meta diária de água',
      menuDataManagement: 'Gerenciamento de dados',
      menuDataManagementSubtitle: 'Migração, exclusão automática e arquivo',
      menuShare: 'Compartilhamento',
      menuShareSubtitle: 'Ativar, gerar e administrar compartilhamentos',
      menuAbout: 'Sobre',
      menuAboutSubtitle: 'Informações do app e desenvolvimento',
      aboutContactTitle: 'Contato',
      aboutSiteLabel: 'Site oficial',
      backBtn: '← Voltar',
      comingSoon: 'Em desenvolvimento',
      // Perfil
      profileNameLabel: 'Seu nome',
      profileNamePlaceholder: 'Como gostaria de ser chamado?',
      profileNameSave: 'Salvar',
      profileNameSaved: 'Nome atualizado',
      profileNamePropagateError: 'Nome salvo neste aparelho, mas não foi possível atualizar nas suas conexões. Verifique a internet e tente de novo.',
      profileAccountLabel: 'Conta Google',
      profileGoogleConnect: 'Conectar com Google',
      profileGoogleConnected: 'Conta Google conectada',
      profileGoogleConnectedDesc: (email: string) => `Conectado como ${email}`,
      profileGoogleDisconnect: 'Desconectar conta Google',
      profileGoogleDisconnectConfirm: 'Desconectar do Google?\n\nO compartilhamento será desativado e todas as suas conexões e listas compartilhadas serão removidas.',
      profileGoogleDisconnectError: 'Não foi possível desconectar sua conta Google agora. Tente novamente.',
      // Preferências
      themeTitle: 'Tema',
      themeAuto: 'Automático',
      themeLight: 'Claro',
      themeDark: 'Escuro',
      accentColorTitle: 'Cor de destaque',
      accentRoxo: 'Roxo',
      accentVermelho: 'Terracota',
      accentAzul: 'Azul',
      accentVerde: 'Verde-água',
      languageTitle: 'Idioma',
      langPt: 'Português',
      langEn: 'English',
      langEs: 'Español',
      // Notificações
      notificationsTitle: '🔔 Notificações',
      notificationsEventsLabel: 'Eventos do dia',
      notificationsToggle: 'Ativar notificações de eventos',
      notificationsMode: 'Modo',
      notificationsModeDaily: 'Matinal',
      notificationsModePerEvent: 'Por evento',
      notificationsTime: 'Horário',
      notificationsLead: 'Antecedência',
      notificationsLeadOptions: ['15 min', '30 min', '1 hora'],
      notificationsPermDenied: 'Permissão negada. Ative as notificações nas configurações do Android.',
      notificationsListsToggle: 'Listas',
      notificationsPendingsToggle: 'Pendências',
      notificationsWaterSection: 'Alerta do contador de hidratação',
      waterReminderToggle: 'Ativar alertas de hidratação',
      // Hidratação
      waterTitle: 'Contador de Hidratação',
      waterEnabledLabel: 'Ativar Contador de Água',
      waterGoalLabel: 'Meta diária',
      waterGoalUnit: 'Litros',
      waterGoalPlaceholder: 'ex: 2,0',
      waterIntervalLabel: 'Alerta a cada',
      waterIntervalUnit: 'minutos',
      waterIntervalPlaceholder: 'ex: 60',
      waterStartTimeLabel: 'Início dos alertas',
      waterEndTimeLabel: 'Fim dos alertas',
      // Gerenciamento de dados
      autoMigrateTitle: 'Migração automática',
      autoMigrateDesc: 'Compromissos passados vão para Pendências. Desativado, ficam como Atrasado.',
      autoMigrateOn: '✅ Ativada (recomendado)',
      autoMigrateOff: '⏸️ Desativada (exibe como Atrasado)',
      autoCleanupTitle: 'Excluir automaticamente após concluir',
      autoDeleteDelayLabel: 'Tempo de espera:',
      autoDeleteDelay1Day: '1 dia',
      autoDeleteDelay1Week: '1 semana',
      autoDeleteDelay1Month: '1 mês',
      deleteEventsRotinasPolicy: 'Compromissos e rotinas',
      deletePendingsPolicy: 'Pendências',
      deletePolicyNever: 'Nunca',
      deletePolicy1Day: 'Após 1 dia',
      deletePolicy1Week: 'Após 1 semana',
      deletePolicy1Month: 'Após 1 mês',
      deleteListsPolicy: 'Listas — após:',
      listsActionLabel: 'Ação para listas concluídas:',
      listsActionDelete: 'Excluir',
      listsActionArchive: 'Arquivar',
      archivedListsTitle: 'Arquivo de listas',
      archivedLists: (n: number) => `📦 Listas Arquivadas (${n})`,
      archivedListsCount: (n: number) => `${n} lista${n !== 1 ? 's' : ''} arquivada${n !== 1 ? 's' : ''}`,
      noArchivedLists: 'Nenhuma lista arquivada',
      noArchivedListsDesc: 'Nenhuma lista arquivada ainda.',
      viewArchivedLists: 'Ver arquivo de listas',
      archivedListItemSingular: 'item',
      archivedListItemPlural: 'itens',
      deleteAllData: 'Apagar dados',
      deletePanelLabel: 'Apagar todos(as):',
      deletePanelLists: 'Listas',
      deletePanelPendencias: 'Pendências',
      deletePanelCompromissos: 'Compromissos',
      deletePanelRotinas: 'Rotinas',
      deletePanelArchivedLists: 'Arquivo de listas',
      deletePanelAll: 'Tudo',
      deletePanelBtn: 'Apagar',
      // Backup
      menuBackup: 'Backup',
      menuBackupSubtitle: 'Frequência, destino e restauração de dados',
      backupDoBackupBtn: 'Fazer Backup',
      backupRestoreBtn: 'Recuperar Backup',
      backupLastBackupLabel: 'Último backup:',
      backupLastBackupNever: 'Nenhum backup realizado ainda',
      backupSuccessTitle: 'Backup concluído',
      backupSuccessLocalMsg: 'Backup salvo em Downloads.',
      backupSuccessCloudMsg: 'Backup salvo na nuvem com sucesso.',
      backupErrorTitle: 'Falha no Backup',
      backupErrorMsg: 'Não foi possível realizar o backup. Tente novamente.',
      backupRestoreConfirmTitle: 'Restaurar Backup',
      backupRestoreConfirmMsg: 'Isso irá substituir todos os dados atuais. Esta ação não pode ser desfeita.',
      backupRestoreConfirmMsgCloud: (date: string) => `Backup de ${date} encontrado na nuvem.\n\nIsso irá substituir todos os dados atuais. Continuar?`,
      backupRestoreSuccess: 'Dados restaurados com sucesso.',
      backupRestoreError: 'Arquivo inválido ou corrompido.',
      backupRestoreNoCloud: 'Nenhum backup encontrado na nuvem para esta conta.',
      backupRestoreNoLocal: 'Nenhum arquivo de backup encontrado em Downloads.',
      backupRestoreSelectTitle: 'Selecionar Backup',
      backupRestoreBtn2: 'Restaurar',
      backupConnectGoogle: 'Conectar Google',
    },
    sharing: {
      disabled: 'Compartilhamento desativado',
      disabledDesc: 'Habilite para compartilhar listas em tempo real com outras pessoas.',
      enableBtn: 'Habilitar compartilhamento',
      requiresGoogleTitle: 'Conecte sua conta Google',
      requiresGoogleMsg: 'O compartilhamento de listas exige uma conta Google. Conecte a sua em Configurações → Perfil.',
      pendingRequests: (n: number) => `🔔 Solicitações pendentes (${n})`,
      pendingRequestsDesc: 'Alguém quer se conectar com você. Aceite ou recuse:',
      accept: 'Aceitar',
      reject: 'Recusar',
      generateCodeTitle: 'Gerar código de convite',
      generateCodeDesc: 'Cada código é de uso único e válido por 24 horas.',
      copyCode: 'Copiar código',
      showQR: 'Mostrar QR',
      closeCode: 'Fechar',
      codeHint: 'Código válido por 24 horas. Após usado ou expirado, gere um novo.',
      generateBtn: 'Gerar código de convite',
      useCodeTitle: 'Usar código de convite',
      useCodeDesc: 'Cole o código que a outra pessoa gerou para você.',
      codePlaceholder: 'Cole o código aqui...',
      requestSent: '✓ Solicitação enviada! Aguarde o aceite.',
      sendRequest: 'Enviar solicitação',
      activeConnections: 'Conexões ativas',
      youInitiated: 'Você iniciou',
      addedYou: 'Te adicionou',
      removeConnection: 'Remover',
      noConnections: 'Nenhuma conexão ativa ainda.\nGere um código para começar.',
      disableBtn: 'Desativar compartilhamento',
      qrTitle: 'QR Code de Convite',
      qrSubtitle: 'Mostre este QR ou compartilhe o código abaixo',
      qrHint: 'A outra pessoa digita o código no campo "Usar código" no app dela. Válido por 24h, uso único.',
      qrClose: 'Fechar',
      disableAlertTitle: 'Desativar compartilhamento',
      disableAlertMsg: 'Isso encerra o compartilhamento de TODAS as listas:\n\n• As suas deixam de aparecer para quem você compartilhou.\n• As compartilhadas com você somem daqui.\n\nSuas conexões são mantidas. Ao reativar, você precisa compartilhar cada lista de novo.',
      disableAlertBtn: 'Desativar',
      disableErrorMsg: 'Não foi possível desativar agora. É preciso conexão com a internet para revogar o compartilhamento com segurança.',
      limitTitle: 'Limite atingido',
      limitMsgGenerate: 'Você já tem um parceiro conectado. Remova a conexão atual antes de convidar outra pessoa.',
      limitMsgConnect: 'Você já tem um parceiro conectado. Remova a conexão atual antes de aceitar um novo convite.',
      copiedTitle: 'Copiado!',
      copiedMsg: 'Código copiado. Envie para a pessoa com quem quer se conectar.',
      codeInvalidTitle: 'Código inválido',
      codeInvalidMsg: 'Código não encontrado ou expirado. Peça um novo código.',
      codeUsedTitle: 'Código já usado',
      codeUsedMsg: 'Este código já foi utilizado. Peça um novo código.',
      ownCodeTitle: 'Erro',
      ownCodeMsg: 'Você não pode usar seu próprio código de convite.',
      alreadyConnectedTitle: 'Já conectados',
      alreadyConnectedMsg: (name: string) => `Você já tem uma conexão com ${name}.`,
      rejectTitle: 'Recusar solicitação',
      rejectMsg: (name: string) => `Recusar conexão de ${name}?`,
      rejectBtn: 'Recusar',
      disconnectTitle: 'Desconectar',
      disconnectMsg: (name: string) => `Encerrar a conexão com ${name}?\n\nTodas as listas compartilhadas entre vocês (nos dois sentidos) deixam de aparecer para os dois. Cada um mantém as listas que criou.`,
      disconnectBtn: 'Desconectar',
      disconnectCleanupError: 'Não foi possível revogar o acesso às listas agora. Verifique sua conexão e tente de novo — a conexão foi mantida.',
      errorGenerate: 'Não foi possível gerar o código. Tente novamente.',
      errorConnect: 'Não foi possível enviar a solicitação. Tente novamente.',
      errorAccept: 'Não foi possível aceitar. Tente novamente.',
      comingSoon: 'Disponível em breve.',
      authErrorMsg: 'Erro de autenticação. Reinicie o app.',
      noDisplayNameMsg: 'Você precisa definir um nome antes de gerar um código. Acesse Configurações → Compartilhamento.',
      modalTitle: 'Compartilhar com',
      modalDisabled: 'O compartilhamento está desativado.\nAtive em Configurações → Compartilhamento.',
      modalNoConnection: 'Nenhuma conexão ativa.\nAdicione um contato em Configurações → Compartilhamento.',
      modalShared: 'Compartilhado',
      modalClose: 'Fechar',
      confirmShareTitle: 'Compartilhar lista',
      confirmShareMsg: (name: string, list: string) => `Compartilhar "${list}" com ${name}?\n\n${name} vai poder ver e editar todos os itens (mas não excluir a lista).`,
      confirmUnshareTitle: 'Parar de compartilhar',
      confirmUnshareMsg: (name: string) => `Parar de compartilhar esta lista com ${name}?\n\nA lista vai sumir do aparelho de ${name} imediatamente.`,
      partnerUnavailableTitle: 'Indisponível',
      partnerUnavailableMsg: (name: string) => `${name} desativou o compartilhamento e não pode receber listas agora. Peça para reativar em Configurações → Compartilhamento.`,
      codeEmptyMsg: 'Digite o código de convite primeiro.',
      connectedOn: (date: string) => `conectado em ${date}`,
    },
    search: {
      title: 'Busca',
      searchBtn: 'Buscar',
      placeholder: 'Buscar eventos, listas...',
      dateDetected: 'Data detectada:',
      goToDate: 'Ir para esta data',
      events: 'COMPROMISSOS',
      lists: 'LISTAS',
      noResults: 'Nenhum resultado para',
      typeToSearch: 'Digite pelo menos 2 caracteres para buscar.',
      subtitle: 'Digite o nome, tag ou data',
      noResultsFound: 'Nenhum resultado encontrado',
      resultsCount: (n: number) => `${n} resultado${n !== 1 ? 's' : ''} encontrado${n !== 1 ? 's' : ''}`,
      sectionEvents: '📅 Eventos e Pendências',
      sectionLists: '📝 Listas',
      pendingLabel: 'Pendente',
      listCompleted: 'Finalizada',
      listOpen: 'Em aberto',
      tipHint: '💡 Dica: Digite uma data (ex: 25/12/2025) para navegar direto para o dia!',
    },
    alerts: {
      deleteEvent: 'Excluir evento',
      deleteEventMsg: (title: string) => `Excluir "${title}"? Esta ação não pode ser desfeita.`,
      unlinkList: 'Desvincular lista',
      unlinkListMsg: 'Deseja remover o vínculo com esta lista?',
      unlinkListBtn: 'Desvincular',
      reopenEvent: 'Reabrir evento',
      reopenEventMsg: 'Este evento está no passado. O que deseja fazer?',
      moveToPending: 'Mover para Pendências',
      reschedule: 'Reagendar',
      linkedListPending: 'Lista pendente',
      linkedListPendingMsg: 'Conclua a lista vinculada antes de concluir este evento.',
      exitShare: 'Sair do compartilhamento',
      exitShareMsg: 'Remover este evento da sua visão? O dono continua com o item.',
      exitShareBtn: 'Sair',
      exitShareList: 'Sair do compartilhamento',
      exitShareListMsg: 'Remover esta lista da sua visão? O dono continua com o item.',
      removeItem: 'Remover item',
      removeItemMsg: 'Deseja remover este item?',
      removeItemBtn: 'Remover',
      reopenList: 'Reabrir lista',
      reopenListMsg: 'Deseja reabrir esta lista?',
      finalizeList: 'Finalizar lista',
      finalizeListMsg: 'Deseja finalizar esta lista?',
      deleteList: 'Excluir lista',
      deleteListMsg: (name: string) => `Excluir "${name}"? Esta ação não pode ser desfeita.`,
      archiveList: 'Arquivar lista',
      archiveListMsg: (name: string) => `Arquivar "${name}"? A lista será removida da tela principal e ficará disponível apenas em Configurações.`,
      archiveListBtn: 'Arquivar',
      archiveListSimpleMsg: (name: string) => `Arquivar "${name}"?`,
      unlinkSimple: 'Desvincular',
      unlinkSimpleMsg: 'Deseja remover o vínculo?',
      deleteWarning: 'Atenção!',
      deleteWarningMsg: 'Os dados selecionados serão permanentemente excluídos. Esta ação não pode ser desfeita.',
      deleteWarningBtn: 'Continuar',
      deleteSure: 'Tem certeza?',
      deleteSureBtn: 'Apagar',
      deleteArchivedList: 'Excluir lista arquivada',
      deleteArchivedListMsg: (name: string) => `Excluir "${name}" permanentemente?`,
      confirm: 'Confirmar',
      postponeEvent: 'Adiar compromisso',
      postponeEventMsg: 'Deseja mover este compromisso para pendências?',
      postponeEventBtn: 'Adiar',
      // Rotinas
      deleteRoutineTitle: 'Excluir rotina',
      deleteRoutineMsg: (title: string) => `Excluir a rotina "${title}" inteira?\n\nTodo o histórico de ocorrências será apagado. Esta ação não pode ser desfeita.`,
      deleteRoutineConfirmTitle: 'Confirmar exclusão',
      deleteRoutineConfirmBtn: 'Excluir mesmo assim',
      suspendRoutineTitle: 'Suspender rotina',
      suspendRoutineMsg: 'A rotina será suspensa. Hoje será concluído automaticamente, e os dias futuros ficarão suspensos até você retomar.',
      suspendRoutineBtn: 'Suspender',
      routineLinkedListTitle: 'Lista pendente',
      routineLinkedListMsg: 'Conclua a lista vinculada antes de concluir esta rotina.',
      unlinkRoutineList: 'Desvincular lista',
      unlinkRoutineListMsg: 'Deseja remover o vínculo com esta lista?',
      reopenRoutineTitle: 'Reabrir ocorrência',
      reopenRoutineMsg: 'Deseja marcar esta ocorrência como não concluída?',
      cantDeleteSharedList: 'Sem permissão',
      cantDeleteSharedListMsg: 'Você não pode excluir uma lista que foi compartilhada com você. Você pode excluir itens, mas para remover a lista inteira use o botão Sair.',
      listNameTaken: 'Nome já usado',
      listNameTakenMsg: 'Não é possível criar a mesma lista no mesmo dia. Escolha um nome diferente ou edite a lista já existente.',
      itemExists: 'Item já na lista',
      itemExistsMsg: (name: string) => `"${name}" já está na lista. Adicionar mesmo assim?`,
      itemExistsAdd: 'Adicionar',
    },
    toast: {
      eventCompleted: 'Compromisso concluído!',
      pendingCompleted: 'Pendência concluída!',
      listCompleted: 'Lista finalizada!',
      listArchived: 'Lista arquivada',
      linked: 'Lista vinculada',
      unlinked: 'Vínculo removido',
      shareEnabled: 'Compartilhamento ativado',
      shareDisabled: 'Compartilhamento desativado',
      undo: 'Desfazer',
      allListItemsDone: 'Todos os itens marcados!',
      syncError: 'Falha ao sincronizar — verifique sua conexão',
      listNoLongerShared: 'Esta lista deixou de ser compartilhada com você',
      reshareHint: (n: number) => `Você tinha ${n} lista${n !== 1 ? 's' : ''} compartilhada${n !== 1 ? 's' : ''}. Compartilhe de novo pelo botão Compartilhar.`,
    },
    onboarding: {
      // Etapa 1 — Idioma + Tema
      welcomeSub: 'Bem-vindo! / Welcome! / ¡Bienvenido!',
      languageLabel: 'Escolha seu idioma:',
      themeLabel: 'Escolha seu tema:',
      themeDark: 'Escuro',
      themeLight: 'Claro',
      themeAuto: 'Automático',
      themeAutoHint: 'Segue as configurações do sistema',
      continueBtn: 'Continuar',
      // Etapa 2 — Google Sign-In
      googleTitle: 'Conecte sua conta',
      googleDesc: 'Entre com sua conta Google para habilitar o compartilhamento de listas em tempo real.\n\nSeu nome será preenchido automaticamente.',
      googleSignInBtn: 'Entrar com Google',
      googleSkipBtn: 'Pular por enquanto',
      googleSkipWarning: 'Sem conta Google, o compartilhamento de listas fica desativado.',
      googleErrorMsg: 'Não conseguimos conectar com sua conta Google agora. Verifique sua internet e tente novamente.',
      // Etapa 2b — Perfil manual
      manualTitle: 'Sobre você',
      manualDesc: 'Preencha suas informações para personalizar o app.',
      manualNameLabel: 'Seu nome ou apelido',
      manualNamePlaceholder: 'Ex: João, Ju...',
      manualLimitationNote: 'O compartilhamento de listas requer conta Google.',
      // Etapa 3 — Compartilhamento
      sharingTitle: 'Compartilhamento',
      sharingDesc: 'Compartilhe listas em tempo real com outras pessoas.\nAs atualizações aparecem instantaneamente para todos os envolvidos.',
      sharingEnableBtn: 'Ativar compartilhamento',
      sharingSkipBtn: 'Agora não',
      sharingHint: 'Você pode ativar depois em Configurações.',
      // Etapa 4 — Backup
      backupTitle: 'Backup de dados',
      backupDesc: 'Escolha como seus dados serão protegidos.',
      backupModeLabel: 'Frequência:',
      backupModeAuto: 'Automático',
      backupModeAutoDesc: 'Salva automaticamente ao usar o app',
      backupModeManual: 'Manual',
      backupModeManualDesc: 'Você decide quando salvar',
      backupLocationLabel: 'Destino:',
      backupLocationLocal: 'Local',
      backupLocationLocalDesc: 'Arquivo no dispositivo',
      backupLocationCloud: 'Nuvem',
      backupLocationCloudDesc: 'Salvo na sua conta Google',
      backupCloudDisabledHint: 'Requer conta Google',
      backupContinueBtn: 'Continuar',
      // Etapa 5 — Hidratação
      waterTitle: 'Contador de Hidratação',
      waterDesc: 'Acompanhe sua meta diária de água e receba lembretes ao longo do dia.\n\nQuando ativo, aparece na tela Hoje com uma garrafa animada.',
      waterEnableBtn: 'Ativar Contador',
      waterSkipBtn: 'Pular',
      waterHint: 'Você pode ativar depois em Configurações.',
      // Etapa 6 — Termos de uso
      termsTitle: 'Termos de Uso',
      termsSubtitle: 'Leia com atenção antes de começar a usar o supLista.',
      termsScrollHint: 'Role até o final para habilitar o botão de aceite.',
      termsAcceptBtn: 'Li e aceito os Termos de Uso',
    },
  },

  en: {
    nav: {
      eventos: 'Events',
      calendario: 'Calendar',
      listas: 'Lists',
      pendencias: 'Pending',
      config: 'Settings',
    },
    common: {
      save: 'Save',
      cancel: 'Cancel',
      edit: 'Edit',
      delete: 'Delete',
      back: '← Back',
      confirm: 'Confirm',
      allDay: 'All Day',
      create: 'Create',
      share: 'Share',
      archive: 'Archive',
      link: 'Link List',
      linkShort: 'Link',
      unlink: 'Unlink',
      complete: 'Complete',
      reopen: 'Reopen',
      suspend: 'Suspend',
      resume: 'Resume',
      postpone: 'Postpone',
      schedule: 'Schedule',
      note: 'Add Note',
      viewList: 'View list',
      done: 'Done',
      pending: 'PENDING',
      late: 'LATE',
      suspended: 'SUSPENDED',
      suspendedBadge: 'SUSPENDED',
      completed: 'Completed',
      open: 'Open',
      today: 'Today',
      notes: 'Notes',
      notesPlaceholder: 'Write a note...',
      linkedList: 'Linked list',
      exit: 'Leave',
      unshare: 'Unshare',
      finalize: 'Finalize',
      pendingLabel: 'Pending',
      error: 'Error',
      detailPending: 'Pending',
      detailEvent: 'Appointment',
      detailRotina: 'Routine',
    },
    home: {
      noEvents: 'No events today',
      sectionEvents: "TODAY'S APPOINTMENTS",
      sectionRoutines: 'MY ROUTINES TODAY',
      sectionRoutinesOtherDay: 'MY ROUTINES FOR THIS DAY',
      sectionToday: "TODAY'S EVENTS",
      sectionTodayOtherDay: 'EVENTS FOR THIS DAY',
      sectionAppointments: 'MY APPOINTMENTS TODAY',
      sectionAppointmentsOtherDay: 'MY APPOINTMENTS FOR THIS DAY',
      createBtn: 'New Event Today',
      emptyTitle: 'All quiet!',
      emptySubtitle: 'No events today.',
      subtitle: (events: number, completed: number) =>
        `${events} event${events !== 1 ? 's' : ''} today . ${completed} completed`,
      allDone: 'All done today',
      // Alternative view
      altMyRoutines: 'Routines',
      altMyAppointments: 'Appointments',
      altOf: 'of',
      altCompleted: 'completed',
      altCompletedPlural: 'completed',
      altActive: 'active',
      altActivePlural: 'active',
      altActiveAppointment: 'active',
      altActiveAppointmentPlural: 'active',
      altCompletedAppointment: 'completed',
      altCompletedAppointmentPlural: 'completed',
      altRoutinesSubtitle: (active: number, completed: number) =>
        `${active} active . ${completed} completed`,
      altAppointmentsSubtitle: (active: number, completed: number) =>
        `${active} active . ${completed} completed`,
      altBack: 'Back',
      // Animation overview
      greetingHello: (name: string) => `Hello ${name},`,
      mantra: 'All done!',
      allDoneSubtitle: 'All commitments for the day completed',
      emptyDaySubtitle: 'No commitments scheduled',
      todayYouHave: 'Today you have:',
      thisDayYouHave: 'On this day you have:',
      bodyTitle: 'My events:',
      myRoutinesLabel: 'Routines',
      myAppointmentsLabel: 'Appointments',
      viewBtn: 'View',
    },
    lists: {
      title: 'supLista',
      createBtn: 'Create new list',
      sectionOpen: 'MY PROGRESS:',
      sectionDone: 'COMPLETED / ARCHIVED',
      createTitle: 'Create List',
      createSubtitle: 'Fill in the list details',
      fieldTitle: 'Title',
      tagLabel: 'Tag',
      typeLabel: 'List Type',
      typeShopping: '🛒 Shopping',
      typeTasks: '📋 Tasks',
      shoppingLabel: 'Shopping',
      tasksLabel: 'Tasks',
      itemsSection: 'ITEMS',
      itemsBtn: 'Items',
      nameLabel: 'List Name *',
      placeholderShopping: 'e.g.: Supermarket, Bakery...',
      placeholderTasks: 'e.g.: Cleaning, Routine...',
      inheritLabel: 'Inherit from previous list (optional)',
      inheritSelect: '+ Select list to inherit',
      inheritModalTitle: 'Inherit from previous list',
      addItem: 'Add Item',
      addTask: 'Add Task',
      finalize: 'Finalize',
      noItems: 'No items yet.\nTap "Add Item" below.',
      subtitle: (total: number, closed: number) =>
        `${total} list${total !== 1 ? 's' : ''} . ${closed} completed`,
      linkedTo: 'Linked to:',
      linkModalTitle: 'Link to Event or Pending',
      linkModalEmpty: 'No events or pending items available.',
      linkTypePending: 'Pending',
      linkTypeEvent: 'Event',
      noneYet: 'No items yet',
      bodyTitle: 'My lists:',
      greetingSubtitle: 'Here are your lists:',
      mantra: 'All clear!',
      emptyTitle: 'All good!',
      emptySubtitle: 'No lists yet.',
      allDoneTitle: 'All clear!',
      allDoneSubtitle: 'No open lists',
    },
    shoppingItem: {
      placeholderShopping: 'e.g.: Rice, Beans...',
      placeholderTask: 'e.g.: Do the dishes, Sweep...',
      qtyLabel: 'Qty:',
      unitLabel: 'Unit:',
      unitPickerTitle: 'Select Unit',
      errorRequired: 'Item name is required',
      priceErrorRequired: 'Enter a valid price',
      priceLabel: 'Price:',
      addPrice: 'Add Price',
      pricePerUnit: 'Per unit',
      priceTotal: 'Total price',
      editItem: 'Edit Item',
      editTask: 'Edit Task',
    },
    units: {
      unidade: 'Unit',
      kg: 'Kg',
      g: 'g',
      litros: 'Liters',
      ml: 'ml',
      mt: 'mt',
      cm: 'cm',
      porção: 'Portion',
      pedaço: 'Piece',
    },
    tags: {
      Trabalho: 'Work',
      Pessoal: 'Personal',
      Saúde: 'Health',
      Família: 'Family',
      Financeiro: 'Financial',
      Estudos: 'Studies',
      Lazer: 'Leisure',
      Outro: 'Other',
      Geral: 'General',
      Personalizar: 'Customize',
      customTagPlaceholder: 'Type your tag...',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Your settings and preferences',
      // Main menu
      menuProfile: 'My Profile',
      menuProfileSubtitle: 'Name and account',
      menuOptions: 'Preferences',
      menuOptionsSubtitle: 'Theme and language',
      menuNotifications: 'Notifications',
      menuNotificationsSubtitle: 'Alerts for events, lists, pending and hydration',
      menuSpecialFeatures: 'Special Features',
      menuSpecialFeaturesSubtitle: 'Hydration and other extra features',
      menuWater: 'Water Tracker',
      menuWaterSubtitle: 'Daily water goal',
      menuDataManagement: 'Data Management',
      menuDataManagementSubtitle: 'Migration, auto-delete and archive',
      menuShare: 'Sharing',
      menuShareSubtitle: 'Enable, generate and manage sharing',
      menuAbout: 'About',
      menuAboutSubtitle: 'App info and development',
      aboutContactTitle: 'Contact',
      aboutSiteLabel: 'Official website',
      backBtn: '← Back',
      comingSoon: 'Coming soon',
      // Profile
      profileNameLabel: 'Your name',
      profileNamePlaceholder: 'What would you like to be called?',
      profileNameSave: 'Save',
      profileNameSaved: 'Name updated',
      profileNamePropagateError: 'Name saved on this device, but it could not be updated in your connections. Check your internet and try again.',
      profileAccountLabel: 'Google Account',
      profileGoogleConnect: 'Connect with Google',
      profileGoogleConnected: 'Google account connected',
      profileGoogleConnectedDesc: (email: string) => `Signed in as ${email}`,
      profileGoogleDisconnect: 'Disconnect Google account',
      profileGoogleDisconnectConfirm: 'Disconnect from Google?\n\nSharing will be turned off and all your connections and shared lists will be removed.',
      profileGoogleDisconnectError: 'Could not disconnect your Google account right now. Please try again.',
      // Preferences
      themeTitle: 'Theme',
      themeAuto: 'Automatic',
      themeLight: 'Light',
      themeDark: 'Dark',
      accentColorTitle: 'Accent color',
      accentRoxo: 'Purple',
      accentVermelho: 'Terracotta',
      accentAzul: 'Blue',
      accentVerde: 'Aqua green',
      languageTitle: 'Language',
      langPt: 'Português',
      langEn: 'English',
      langEs: 'Español',
      // Notifications
      notificationsTitle: '🔔 Notifications',
      notificationsEventsLabel: 'Events',
      notificationsToggle: 'Enable event notifications',
      notificationsMode: 'Mode',
      notificationsModeDaily: 'Morning',
      notificationsModePerEvent: 'Per event',
      notificationsTime: 'Time',
      notificationsLead: 'Lead time',
      notificationsLeadOptions: ['15 min', '30 min', '1 hour'],
      notificationsPermDenied: 'Permission denied. Enable notifications in Android settings.',
      notificationsListsToggle: 'Lists',
      notificationsPendingsToggle: 'Pending',
      notificationsWaterSection: 'Water tracker alert',
      waterReminderToggle: 'Enable hydration alerts',
      // Hydration
      waterTitle: 'Water Tracker',
      waterEnabledLabel: 'Enable Water Tracker',
      waterGoalLabel: 'Daily goal',
      waterGoalUnit: 'fl oz',
      waterGoalPlaceholder: 'e.g. 67.6',
      waterIntervalLabel: 'Alert every',
      waterIntervalUnit: 'minutes',
      waterIntervalPlaceholder: 'e.g. 60',
      waterStartTimeLabel: 'Alert start time',
      waterEndTimeLabel: 'Alert end time',
      // Data management
      autoMigrateTitle: 'Auto migration',
      autoMigrateDesc: 'Past events move to Pending. When off, they show as Late.',
      autoMigrateOn: '✅ Enabled (recommended)',
      autoMigrateOff: '⏸️ Disabled (shows as Late)',
      autoCleanupTitle: 'Auto-delete after completing',
      autoDeleteDelayLabel: 'Wait time:',
      autoDeleteDelay1Day: '1 day',
      autoDeleteDelay1Week: '1 week',
      autoDeleteDelay1Month: '1 month',
      deleteEventsRotinasPolicy: 'Events and routines',
      deletePendingsPolicy: 'Pending',
      deletePolicyNever: 'Never',
      deletePolicy1Day: 'After 1 day',
      deletePolicy1Week: 'After 1 week',
      deletePolicy1Month: 'After 1 month',
      deleteListsPolicy: 'Lists — after:',
      listsActionLabel: 'Action for completed lists:',
      listsActionDelete: 'Delete',
      listsActionArchive: 'Archive',
      archivedListsTitle: 'Archived lists',
      archivedLists: (n: number) => `📦 Archived Lists (${n})`,
      archivedListsCount: (n: number) => `${n} archived list${n !== 1 ? 's' : ''}`,
      noArchivedLists: 'No archived lists',
      noArchivedListsDesc: 'No archived lists yet.',
      viewArchivedLists: 'View lists archive',
      archivedListItemSingular: 'item',
      archivedListItemPlural: 'items',
      deleteAllData: 'Delete data',
      deletePanelLabel: 'Delete all:',
      deletePanelLists: 'Lists',
      deletePanelPendencias: 'Pending',
      deletePanelCompromissos: 'Events',
      deletePanelRotinas: 'Routines',
      deletePanelArchivedLists: 'Archived lists',
      deletePanelAll: 'Everything',
      deletePanelBtn: 'Delete',
      // Backup
      menuBackup: 'Backup',
      menuBackupSubtitle: 'Frequency, destination and data restore',
      backupDoBackupBtn: 'Backup Now',
      backupRestoreBtn: 'Restore Backup',
      backupLastBackupLabel: 'Last backup:',
      backupLastBackupNever: 'No backup made yet',
      backupSuccessTitle: 'Backup complete',
      backupSuccessLocalMsg: 'Backup saved to Downloads.',
      backupSuccessCloudMsg: 'Backup saved to the cloud successfully.',
      backupErrorTitle: 'Backup failed',
      backupErrorMsg: 'Could not complete the backup. Please try again.',
      backupRestoreConfirmTitle: 'Restore Backup',
      backupRestoreConfirmMsg: 'This will replace all current data. This action cannot be undone.',
      backupRestoreConfirmMsgCloud: (date: string) => `Backup from ${date} found in the cloud.\n\nThis will replace all current data. Continue?`,
      backupRestoreSuccess: 'Data restored successfully.',
      backupRestoreError: 'Invalid or corrupted backup file.',
      backupRestoreNoCloud: 'No backup found in the cloud for this account.',
      backupRestoreNoLocal: 'No backup file found in Downloads.',
      backupRestoreSelectTitle: 'Select Backup',
      backupRestoreBtn2: 'Restore',
      backupConnectGoogle: 'Connect Google',
    },
    sharing: {
      disabled: 'Sharing disabled',
      disabledDesc: 'Enable to share lists in real time with other people.',
      enableBtn: 'Enable sharing',
      requiresGoogleTitle: 'Connect your Google account',
      requiresGoogleMsg: 'List sharing requires a Google account. Connect yours in Settings → Profile.',
      pendingRequests: (n: number) => `🔔 Pending requests (${n})`,
      pendingRequestsDesc: 'Someone wants to connect with you. Accept or decline:',
      accept: 'Accept',
      reject: 'Decline',
      generateCodeTitle: 'Generate invite code',
      generateCodeDesc: 'Each code is single-use and valid for 24 hours.',
      copyCode: 'Copy code',
      showQR: 'Show QR',
      closeCode: 'Close',
      codeHint: 'Code valid for 24 hours. After used or expired, generate a new one.',
      generateBtn: 'Generate invite code',
      useCodeTitle: 'Use invite code',
      useCodeDesc: 'Paste the code the other person generated for you.',
      codePlaceholder: 'Paste the code here...',
      requestSent: '✓ Request sent! Waiting for acceptance.',
      sendRequest: 'Send request',
      activeConnections: 'Active connections',
      youInitiated: 'You initiated',
      addedYou: 'Added you',
      removeConnection: 'Remove',
      noConnections: 'No active connections yet.\nGenerate a code to get started.',
      disableBtn: 'Disable sharing',
      qrTitle: 'Invite QR Code',
      qrSubtitle: 'Show this QR or share the code below',
      qrHint: 'The other person types the code in the "Use code" field in their app. Valid for 24h, single use.',
      qrClose: 'Close',
      disableAlertTitle: 'Disable sharing',
      disableAlertMsg: 'This ends sharing for ALL lists:\n\n• Yours stop appearing for the people you shared with.\n• Lists shared with you disappear from here.\n\nYour connections are kept. When you turn it back on, you must share each list again.',
      disableAlertBtn: 'Disable',
      disableErrorMsg: "Couldn't disable right now. An internet connection is required to revoke sharing safely.",
      limitTitle: 'Limit reached',
      limitMsgGenerate: 'You already have a connected partner. Remove the current connection before inviting someone else.',
      limitMsgConnect: 'You already have a connected partner. Remove the current connection before accepting a new invite.',
      copiedTitle: 'Copied!',
      copiedMsg: 'Code copied. Send it to the person you want to connect with.',
      codeInvalidTitle: 'Invalid code',
      codeInvalidMsg: 'Code not found or expired. Ask for a new code.',
      codeUsedTitle: 'Code already used',
      codeUsedMsg: 'This code has already been used. Ask for a new code.',
      ownCodeTitle: 'Error',
      ownCodeMsg: 'You cannot use your own invite code.',
      alreadyConnectedTitle: 'Already connected',
      alreadyConnectedMsg: (name: string) => `You already have a connection with ${name}.`,
      rejectTitle: 'Decline request',
      rejectMsg: (name: string) => `Decline connection from ${name}?`,
      rejectBtn: 'Decline',
      disconnectTitle: 'Disconnect',
      disconnectMsg: (name: string) => `End the connection with ${name}?\n\nEvery list shared between you (both directions) will stop appearing for both of you. Each keeps the lists they created.`,
      disconnectBtn: 'Disconnect',
      disconnectCleanupError: "Couldn't revoke access to the lists right now. Check your connection and try again — the connection was kept.",
      errorGenerate: 'Could not generate the code. Please try again.',
      errorConnect: 'Could not send the request. Please try again.',
      errorAccept: 'Could not accept. Please try again.',
      comingSoon: 'Coming soon.',
      authErrorMsg: 'Authentication error. Restart the app.',
      noDisplayNameMsg: 'You need to set a display name before generating a code. Go to Settings → Sharing.',
      modalTitle: 'Share with',
      modalDisabled: 'Sharing is disabled.\nEnable it in Settings → Sharing.',
      modalNoConnection: 'No active connection.\nAdd a contact in Settings → Sharing.',
      modalShared: 'Shared',
      modalClose: 'Close',
      confirmShareTitle: 'Share list',
      confirmShareMsg: (name: string, list: string) => `Share "${list}" with ${name}?\n\n${name} will be able to view and edit every item (but not delete the list).`,
      confirmUnshareTitle: 'Stop sharing',
      confirmUnshareMsg: (name: string) => `Stop sharing this list with ${name}?\n\nThe list will disappear from ${name}'s device right away.`,
      partnerUnavailableTitle: 'Unavailable',
      partnerUnavailableMsg: (name: string) => `${name} turned sharing off and can't receive lists right now. Ask them to turn it back on in Settings → Sharing.`,
      codeEmptyMsg: 'Enter the invite code first.',
      connectedOn: (date: string) => `connected on ${date}`,
    },
    search: {
      title: 'Search',
      searchBtn: 'Search',
      placeholder: 'Search events, lists...',
      dateDetected: 'Date detected:',
      goToDate: 'Go to this date',
      events: 'EVENTS',
      lists: 'LISTS',
      noResults: 'No results for',
      typeToSearch: 'Type at least 2 characters to search.',
      subtitle: 'Type name, tag or date',
      noResultsFound: 'No results found',
      resultsCount: (n: number) => `${n} result${n !== 1 ? 's' : ''} found`,
      sectionEvents: '📅 Events & Pending',
      sectionLists: '📝 Lists',
      pendingLabel: 'Pending',
      listCompleted: 'Completed',
      listOpen: 'Open',
      tipHint: '💡 Tip: Type a date (e.g.: 12/25/2025) to go directly to that day!',
    },
    alerts: {
      deleteEvent: 'Delete event',
      deleteEventMsg: (title: string) => `Delete "${title}"? This action cannot be undone.`,
      unlinkList: 'Unlink list',
      unlinkListMsg: 'Remove the link with this list?',
      unlinkListBtn: 'Unlink',
      reopenEvent: 'Reopen event',
      reopenEventMsg: 'This event is in the past. What do you want to do?',
      moveToPending: 'Move to Pending',
      reschedule: 'Reschedule',
      linkedListPending: 'Pending list',
      linkedListPendingMsg: 'Complete the linked list before completing this event.',
      exitShare: 'Leave sharing',
      exitShareMsg: 'Remove this event from your view? The owner keeps the item.',
      exitShareBtn: 'Leave',
      exitShareList: 'Leave sharing',
      exitShareListMsg: 'Remove this list from your view? The owner keeps the item.',
      removeItem: 'Remove item',
      removeItemMsg: 'Remove this item?',
      removeItemBtn: 'Remove',
      reopenList: 'Reopen list',
      reopenListMsg: 'Reopen this list?',
      finalizeList: 'Finalize list',
      finalizeListMsg: 'Finalize this list?',
      deleteList: 'Delete list',
      deleteListMsg: (name: string) => `Delete "${name}"? This action cannot be undone.`,
      archiveList: 'Archive list',
      archiveListMsg: (name: string) => `Archive "${name}"? The list will be removed from the main screen and only available in Settings.`,
      archiveListBtn: 'Archive',
      archiveListSimpleMsg: (name: string) => `Archive "${name}"?`,
      unlinkSimple: 'Unlink',
      unlinkSimpleMsg: 'Remove the link?',
      deleteWarning: 'Warning!',
      deleteWarningMsg: 'The selected data will be permanently deleted. This action cannot be undone.',
      deleteWarningBtn: 'Continue',
      deleteSure: 'Are you sure?',
      deleteSureBtn: 'Delete',
      deleteArchivedList: 'Delete archived list',
      deleteArchivedListMsg: (name: string) => `Permanently delete "${name}"?`,
      confirm: 'Confirm',
      postponeEvent: 'Postpone event',
      postponeEventMsg: 'Move this event to Pending?',
      postponeEventBtn: 'Postpone',
      // Routines
      deleteRoutineTitle: 'Delete routine',
      deleteRoutineMsg: (title: string) => `Delete the entire routine "${title}"?\n\nAll occurrence history will be erased. This action cannot be undone.`,
      deleteRoutineConfirmTitle: 'Confirm deletion',
      deleteRoutineConfirmBtn: 'Delete anyway',
      suspendRoutineTitle: 'Suspend routine',
      suspendRoutineMsg: 'The routine will be suspended. Today will be completed automatically, and future days will be suspended until you resume.',
      suspendRoutineBtn: 'Suspend',
      routineLinkedListTitle: 'Pending list',
      routineLinkedListMsg: 'Complete the linked list before completing this routine.',
      unlinkRoutineList: 'Unlink list',
      unlinkRoutineListMsg: 'Remove the link with this list?',
      reopenRoutineTitle: 'Reopen occurrence',
      reopenRoutineMsg: 'Mark this occurrence as not completed?',
      cantDeleteSharedList: 'Not allowed',
      cantDeleteSharedListMsg: 'You cannot delete a list that was shared with you. You can delete items, but to remove the whole list use the Leave button.',
      listNameTaken: 'Name already used',
      listNameTakenMsg: "You can't create the same list on the same day. Choose a different name or edit the existing list.",
      itemExists: 'Item already in list',
      itemExistsMsg: (name: string) => `"${name}" is already in the list. Add it anyway?`,
      itemExistsAdd: 'Add',
    },
    toast: {
      eventCompleted: 'Event completed!',
      pendingCompleted: 'Task completed!',
      listCompleted: 'List finalized!',
      listArchived: 'List archived',
      linked: 'List linked',
      unlinked: 'Link removed',
      shareEnabled: 'Sharing enabled',
      shareDisabled: 'Sharing disabled',
      undo: 'Undo',
      allListItemsDone: 'All items checked!',
      syncError: 'Sync failed — check your connection',
      listNoLongerShared: 'This list is no longer shared with you',
      reshareHint: (n: number) => `You had ${n} shared list${n !== 1 ? 's' : ''}. Share them again with the Share button.`,
    },
    onboarding: {
      // Step 1 — Language + Theme
      welcomeSub: 'Welcome! / Bem-vindo! / ¡Bienvenido!',
      languageLabel: 'Choose your language:',
      themeLabel: 'Choose your theme:',
      themeDark: 'Dark',
      themeLight: 'Light',
      themeAuto: 'Auto',
      themeAutoHint: 'Follows your system settings',
      continueBtn: 'Continue',
      // Step 2 — Google Sign-In
      googleTitle: 'Connect your account',
      googleDesc: 'Sign in with your Google account to enable real-time list sharing.\n\nYour name will be filled in automatically.',
      googleSignInBtn: 'Sign in with Google',
      googleSkipBtn: 'Skip for now',
      googleSkipWarning: 'Without a Google account, list sharing will be disabled.',
      googleErrorMsg: "We couldn't connect to your Google account right now. Check your internet connection and try again.",
      // Step 2b — Manual Profile
      manualTitle: 'About you',
      manualDesc: 'Fill in your information to personalize the app.',
      manualNameLabel: 'Your name or nickname',
      manualNamePlaceholder: 'e.g.: John, Jo...',
      manualLimitationNote: 'List sharing requires a Google account.',
      // Step 3 — Sharing
      sharingTitle: 'Sharing',
      sharingDesc: 'Share lists in real time with other people.\nUpdates appear instantly for everyone involved.',
      sharingEnableBtn: 'Enable sharing',
      sharingSkipBtn: 'Not now',
      sharingHint: 'You can enable it later in Settings.',
      // Step 4 — Backup
      backupTitle: 'Data backup',
      backupDesc: 'Choose how your data will be protected.',
      backupModeLabel: 'Frequency:',
      backupModeAuto: 'Automatic',
      backupModeAutoDesc: 'Saves on every change',
      backupModeManual: 'Manual',
      backupModeManualDesc: 'You decide when to save',
      backupLocationLabel: 'Destination:',
      backupLocationLocal: 'Local',
      backupLocationLocalDesc: 'File on device',
      backupLocationCloud: 'Cloud',
      backupLocationCloudDesc: 'Saved to your Google account',
      backupCloudDisabledHint: 'Requires Google account',
      backupContinueBtn: 'Continue',
      // Step 5 — Water
      waterTitle: 'Water Tracker',
      waterDesc: 'Track your daily water goal and receive reminders throughout the day.\n\nWhen active, appears on the Today screen with an animated bottle.',
      waterEnableBtn: 'Enable Tracker',
      waterSkipBtn: 'Skip',
      waterHint: 'You can enable it later in Settings.',
      // Step 6 — Terms
      termsTitle: 'Terms of Use',
      termsSubtitle: 'Read carefully before using supLista.',
      termsScrollHint: 'Scroll to the bottom to enable the accept button.',
      termsAcceptBtn: 'I have read and accept the Terms of Use',
    },
  },

  es: {
    nav: {
      eventos: 'Eventos',
      calendario: 'Calendario',
      listas: 'Listas',
      pendencias: 'Pendientes',
      config: 'Config',
    },
    common: {
      save: 'Guardar',
      cancel: 'Cancelar',
      edit: 'Editar',
      delete: 'Eliminar',
      back: '← Volver',
      confirm: 'Confirmar',
      allDay: 'Todo el Día',
      create: 'Crear',
      share: 'Compartir',
      archive: 'Archivar',
      link: 'Vincular Lista',
      linkShort: 'Vincular',
      unlink: 'Desvincular',
      complete: 'Completar',
      reopen: 'Reabrir',
      suspend: 'Suspender',
      resume: 'Reanudar',
      postpone: 'Aplazar',
      schedule: 'Programar',
      note: 'Anotar',
      viewList: 'Ver lista',
      done: 'Completado',
      pending: 'PENDIENTE',
      late: 'ATRASADO',
      suspended: 'SUSPENDIDA',
      suspendedBadge: 'SUSPENDIDO',
      completed: 'Completada',
      open: 'Abierta',
      today: 'Hoy',
      notes: 'Anotaciones',
      notesPlaceholder: 'Escribe una anotación...',
      linkedList: 'Lista vinculada',
      exit: 'Salir',
      unshare: 'Dejar de compartir',
      finalize: 'Finalizar',
      pendingLabel: 'Pendiente',
      error: 'Error',
      detailPending: 'Pendiente',
      detailEvent: 'Compromiso',
      detailRotina: 'Rutina',
    },
    home: {
      noEvents: 'Sin compromisos hoy',
      sectionEvents: 'COMPROMISOS DE HOY',
      sectionRoutines: 'MIS RUTINAS DE HOY',
      sectionRoutinesOtherDay: 'MIS RUTINAS DE ESTE DÍA',
      sectionToday: 'EVENTOS DE HOY',
      sectionTodayOtherDay: 'EVENTOS DE ESTE DÍA',
      sectionAppointments: 'MIS COMPROMISOS DE HOY',
      sectionAppointmentsOtherDay: 'MIS COMPROMISOS DE ESTE DÍA',
      createBtn: 'Nuevo Evento Hoy',
      emptyTitle: '¡Todo en paz!',
      emptySubtitle: 'Sin eventos hoy.',
      subtitle: (events: number, completed: number) =>
        `${events} evento${events !== 1 ? 's' : ''} hoy . ${completed} completado${completed !== 1 ? 's' : ''}`,
      allDone: 'Todo completado hoy',
      // Vista alternativa
      altMyRoutines: 'Rutinas',
      altMyAppointments: 'Compromisos',
      altOf: 'de',
      altCompleted: 'completada',
      altCompletedPlural: 'completadas',
      altActive: 'activa',
      altActivePlural: 'activas',
      altActiveAppointment: 'activo',
      altActiveAppointmentPlural: 'activos',
      altCompletedAppointment: 'completado',
      altCompletedAppointmentPlural: 'completados',
      altRoutinesSubtitle: (active: number, completed: number) =>
        `${active} activa${active !== 1 ? 's' : ''} . ${completed} completada${completed !== 1 ? 's' : ''}`,
      altAppointmentsSubtitle: (active: number, completed: number) =>
        `${active} activo${active !== 1 ? 's' : ''} . ${completed} completado${completed !== 1 ? 's' : ''}`,
      altBack: 'Volver',
      // Animación overview
      greetingHello: (name: string) => `¡Hola ${name},`,
      mantra: '¡Todo listo!',
      allDoneSubtitle: 'Todos los compromisos del día completados',
      emptyDaySubtitle: 'Sin compromisos programados',
      todayYouHave: 'Hoy tienes:',
      thisDayYouHave: 'En este día tienes:',
      bodyTitle: 'Mis eventos:',
      myRoutinesLabel: 'Rutinas',
      myAppointmentsLabel: 'Compromisos',
      viewBtn: 'Ver',
    },
    lists: {
      title: 'supLista',
      createBtn: 'Crear nueva lista',
      sectionOpen: 'MI PROGRESO:',
      sectionDone: 'COMPLETADAS / ARCHIVADAS',
      createTitle: 'Crear Lista',
      createSubtitle: 'Completa los detalles de la lista',
      fieldTitle: 'Título',
      tagLabel: 'Etiqueta',
      typeLabel: 'Tipo de Lista',
      typeShopping: '🛒 Compras',
      typeTasks: '📋 Tareas',
      shoppingLabel: 'Compras',
      tasksLabel: 'Tareas',
      itemsSection: 'ARTÍCULOS',
      itemsBtn: 'Artículos',
      nameLabel: 'Nombre de la Lista *',
      placeholderShopping: 'Ej: Supermercado, Panadería...',
      placeholderTasks: 'Ej: Limpieza, Rutina...',
      inheritLabel: 'Heredar de lista anterior (opcional)',
      inheritSelect: '+ Seleccionar lista para heredar',
      inheritModalTitle: 'Heredar de lista anterior',
      addItem: 'Agregar Artículo',
      addTask: 'Agregar Tarea',
      finalize: 'Finalizar',
      noItems: 'Sin artículos aún.\nToca "Agregar Artículo" abajo.',
      subtitle: (total: number, closed: number) =>
        `${total} lista${total !== 1 ? 's' : ''} . ${closed} completada${closed !== 1 ? 's' : ''}`,
      linkedTo: 'Vinculada a:',
      linkModalTitle: 'Vincular a Evento o Pendiente',
      linkModalEmpty: 'Sin eventos ni pendientes disponibles.',
      linkTypePending: 'Pendiente',
      linkTypeEvent: 'Evento',
      noneYet: 'Sin artículos aún',
      bodyTitle: 'Mis listas:',
      greetingSubtitle: 'Estas son tus listas:',
      mantra: '¡Todo en orden!',
      emptyTitle: '¡Todo bien!',
      emptySubtitle: 'Sin listas aún.',
      allDoneTitle: '¡Todo en orden!',
      allDoneSubtitle: 'Sin listas abiertas',
    },
    shoppingItem: {
      placeholderShopping: 'Ej: Arroz, Frijoles...',
      placeholderTask: 'Ej: Lavar los platos, Barrer...',
      qtyLabel: 'Cant:',
      unitLabel: 'Unidad:',
      unitPickerTitle: 'Seleccionar Unidad',
      errorRequired: 'El nombre del artículo es obligatorio',
      priceErrorRequired: 'Ingresa un precio válido',
      priceLabel: 'Precio:',
      addPrice: 'Agregar Precio',
      pricePerUnit: 'Por unidad',
      priceTotal: 'Precio total',
      editItem: 'Editar Artículo',
      editTask: 'Editar Tarea',
    },
    units: {
      unidade: 'Unidad',
      kg: 'Kg',
      g: 'g',
      litros: 'Litros',
      ml: 'ml',
      mt: 'mt',
      cm: 'cm',
      porção: 'Porción',
      pedaço: 'Pieza',
    },
    tags: {
      Trabalho: 'Trabajo',
      Pessoal: 'Personal',
      Saúde: 'Salud',
      Família: 'Familia',
      Financeiro: 'Financiero',
      Estudos: 'Estudios',
      Lazer: 'Ocio',
      Outro: 'Otro',
      Geral: 'General',
      Personalizar: 'Personalizar',
      customTagPlaceholder: 'Escribe tu etiqueta...',
    },
    settings: {
      title: 'Configuración',
      subtitle: 'Tus ajustes y preferencias',
      // Menú principal
      menuProfile: 'Mi Perfil',
      menuProfileSubtitle: 'Nombre y cuenta',
      menuOptions: 'Preferencias',
      menuOptionsSubtitle: 'Tema e idioma',
      menuNotifications: 'Notificaciones',
      menuNotificationsSubtitle: 'Alertas de eventos, listas, pendientes e hidratación',
      menuSpecialFeatures: 'Funciones Especiales',
      menuSpecialFeaturesSubtitle: 'Hidratación y otras funciones extra',
      menuWater: 'Contador de Hidratación',
      menuWaterSubtitle: 'Meta diaria de agua',
      menuDataManagement: 'Gestión de datos',
      menuDataManagementSubtitle: 'Migración, eliminación automática y archivo',
      menuShare: 'Compartir',
      menuShareSubtitle: 'Activar, generar y administrar compartidos',
      menuAbout: 'Acerca de',
      menuAboutSubtitle: 'Información del app y desarrollo',
      aboutContactTitle: 'Contacto',
      aboutSiteLabel: 'Sitio oficial',
      backBtn: '← Volver',
      comingSoon: 'En desarrollo',
      // Perfil
      profileNameLabel: 'Tu nombre',
      profileNamePlaceholder: '¿Cómo te gustaría que te llamaran?',
      profileNameSave: 'Guardar',
      profileNameSaved: 'Nombre actualizado',
      profileNamePropagateError: 'Nombre guardado en este dispositivo, pero no se pudo actualizar en tus conexiones. Revisa tu internet e inténtalo de nuevo.',
      profileAccountLabel: 'Cuenta Google',
      profileGoogleConnect: 'Conectar con Google',
      profileGoogleConnected: 'Cuenta Google conectada',
      profileGoogleConnectedDesc: (email: string) => `Sesión iniciada como ${email}`,
      profileGoogleDisconnect: 'Desconectar cuenta Google',
      profileGoogleDisconnectConfirm: '¿Desconectar de Google?\n\nEl compartido se desactivará y se eliminarán todas tus conexiones y listas compartidas.',
      profileGoogleDisconnectError: 'No se pudo desconectar tu cuenta de Google ahora. Intenta de nuevo.',
      // Preferencias
      themeTitle: 'Tema',
      themeAuto: 'Automático',
      themeLight: 'Claro',
      themeDark: 'Oscuro',
      accentColorTitle: 'Color de acento',
      accentRoxo: 'Morado',
      accentVermelho: 'Terracota',
      accentAzul: 'Azul',
      accentVerde: 'Verde agua',
      languageTitle: 'Idioma',
      langPt: 'Português',
      langEn: 'English',
      langEs: 'Español',
      // Notificaciones
      notificationsTitle: '🔔 Notificaciones',
      notificationsEventsLabel: 'Eventos del día',
      notificationsToggle: 'Activar notificaciones de eventos',
      notificationsMode: 'Modo',
      notificationsModeDaily: 'Matinal',
      notificationsModePerEvent: 'Por evento',
      notificationsTime: 'Horario',
      notificationsLead: 'Anticipación',
      notificationsLeadOptions: ['15 min', '30 min', '1 hora'],
      notificationsPermDenied: 'Permiso denegado. Activa las notificaciones en la configuración de Android.',
      notificationsListsToggle: 'Listas',
      notificationsPendingsToggle: 'Pendientes',
      notificationsWaterSection: 'Alerta del contador de hidratación',
      waterReminderToggle: 'Activar alertas de hidratación',
      // Hidratación
      waterTitle: 'Contador de Hidratación',
      waterEnabledLabel: 'Activar Contador de Agua',
      waterGoalLabel: 'Meta diaria',
      waterGoalUnit: 'Litros',
      waterGoalPlaceholder: 'ej: 2,0',
      waterIntervalLabel: 'Alerta cada',
      waterIntervalUnit: 'minutos',
      waterIntervalPlaceholder: 'ej: 60',
      waterStartTimeLabel: 'Inicio de alertas',
      waterEndTimeLabel: 'Fin de alertas',
      // Gestión de datos
      autoMigrateTitle: 'Migración automática',
      autoMigrateDesc: 'Compromisos pasados van a Pendientes. Desactivado, se muestran como Atrasado.',
      autoMigrateOn: '✅ Activada (recomendado)',
      autoMigrateOff: '⏸️ Desactivada (muestra como Atrasado)',
      autoCleanupTitle: 'Eliminar automáticamente al completar',
      autoDeleteDelayLabel: 'Tiempo de espera:',
      autoDeleteDelay1Day: '1 día',
      autoDeleteDelay1Week: '1 semana',
      autoDeleteDelay1Month: '1 mes',
      deleteEventsRotinasPolicy: 'Compromisos y rutinas',
      deletePendingsPolicy: 'Pendientes',
      deletePolicyNever: 'Nunca',
      deletePolicy1Day: 'Después de 1 día',
      deletePolicy1Week: 'Después de 1 semana',
      deletePolicy1Month: 'Después de 1 mes',
      deleteListsPolicy: 'Listas — después de:',
      listsActionLabel: 'Acción para listas completadas:',
      listsActionDelete: 'Eliminar',
      listsActionArchive: 'Archivar',
      archivedListsTitle: 'Archivo de listas',
      archivedLists: (n: number) => `📦 Listas Archivadas (${n})`,
      archivedListsCount: (n: number) => `${n} lista${n !== 1 ? 's' : ''} archivada${n !== 1 ? 's' : ''}`,
      noArchivedLists: 'Sin listas archivadas',
      noArchivedListsDesc: 'Sin listas archivadas aún.',
      viewArchivedLists: 'Ver archivo de listas',
      archivedListItemSingular: 'elemento',
      archivedListItemPlural: 'elementos',
      deleteAllData: 'Borrar datos',
      deletePanelLabel: 'Borrar todos(as):',
      deletePanelLists: 'Listas',
      deletePanelPendencias: 'Pendientes',
      deletePanelCompromissos: 'Compromisos',
      deletePanelRotinas: 'Rutinas',
      deletePanelArchivedLists: 'Archivo de listas',
      deletePanelAll: 'Todo',
      deletePanelBtn: 'Borrar',
      // Backup
      menuBackup: 'Copia de seguridad',
      menuBackupSubtitle: 'Frecuencia, destino y restauración de datos',
      backupDoBackupBtn: 'Hacer copia',
      backupRestoreBtn: 'Recuperar copia',
      backupLastBackupLabel: 'Última copia:',
      backupLastBackupNever: 'Aún no se ha realizado ninguna copia',
      backupSuccessTitle: 'Copia completada',
      backupSuccessLocalMsg: 'Copia guardada en Descargas.',
      backupSuccessCloudMsg: 'Copia de seguridad guardada en la nube.',
      backupErrorTitle: 'Error al hacer copia',
      backupErrorMsg: 'No se pudo realizar la copia de seguridad. Intenta de nuevo.',
      backupRestoreConfirmTitle: 'Restaurar copia',
      backupRestoreConfirmMsg: 'Esto reemplazará todos los datos actuales. Esta acción no se puede deshacer.',
      backupRestoreConfirmMsgCloud: (date: string) => `Copia del ${date} encontrada en la nube.\n\n¿Reemplazar todos los datos actuales?`,
      backupRestoreSuccess: 'Datos restaurados correctamente.',
      backupRestoreError: 'Archivo de copia inválido o corrupto.',
      backupRestoreNoCloud: 'No se encontró ninguna copia en la nube para esta cuenta.',
      backupRestoreNoLocal: 'No se encontró ningún archivo de copia en Descargas.',
      backupRestoreSelectTitle: 'Seleccionar copia',
      backupRestoreBtn2: 'Restaurar',
      backupConnectGoogle: 'Conectar Google',
    },
    sharing: {
      disabled: 'Compartición desactivada',
      disabledDesc: 'Habilita para compartir listas en tiempo real con otras personas.',
      enableBtn: 'Habilitar compartición',
      requiresGoogleTitle: 'Conecta tu cuenta de Google',
      requiresGoogleMsg: 'Compartir listas requiere una cuenta de Google. Conéctala en Configuración → Perfil.',
      pendingRequests: (n: number) => `🔔 Solicitudes pendientes (${n})`,
      pendingRequestsDesc: 'Alguien quiere conectarse contigo. Acepta o rechaza:',
      accept: 'Aceptar',
      reject: 'Rechazar',
      generateCodeTitle: 'Generar código de invitación',
      generateCodeDesc: 'Cada código es de un solo uso y válido por 24 horas.',
      copyCode: 'Copiar código',
      showQR: 'Mostrar QR',
      closeCode: 'Cerrar',
      codeHint: 'Código válido por 24 horas. Tras su uso o expiración, genera uno nuevo.',
      generateBtn: 'Generar código de invitación',
      useCodeTitle: 'Usar código de invitación',
      useCodeDesc: 'Pega el código que la otra persona generó para ti.',
      codePlaceholder: 'Pega el código aquí...',
      requestSent: '✓ ¡Solicitud enviada! Esperando aceptación.',
      sendRequest: 'Enviar solicitud',
      activeConnections: 'Conexiones activas',
      youInitiated: 'Tú iniciaste',
      addedYou: 'Te agregó',
      removeConnection: 'Eliminar',
      noConnections: 'Sin conexiones activas aún.\nGenera un código para comenzar.',
      disableBtn: 'Desactivar compartición',
      qrTitle: 'Código QR de Invitación',
      qrSubtitle: 'Muestra este QR o comparte el código de abajo',
      qrHint: 'La otra persona escribe el código en el campo "Usar código" en su app. Válido por 24h, uso único.',
      qrClose: 'Cerrar',
      disableAlertTitle: 'Desactivar compartición',
      disableAlertMsg: 'Esto termina la compartición de TODAS las listas:\n\n• Las tuyas dejan de aparecer para quienes compartiste.\n• Las compartidas contigo desaparecen de aquí.\n\nTus conexiones se mantienen. Al reactivar, debes compartir cada lista de nuevo.',
      disableAlertBtn: 'Desactivar',
      disableErrorMsg: 'No se pudo desactivar ahora. Se necesita conexión a internet para revocar la compartición de forma segura.',
      limitTitle: 'Límite alcanzado',
      limitMsgGenerate: 'Ya tienes un socio conectado. Elimina la conexión actual antes de invitar a otra persona.',
      limitMsgConnect: 'Ya tienes un socio conectado. Elimina la conexión actual antes de aceptar una nueva invitación.',
      copiedTitle: '¡Copiado!',
      copiedMsg: 'Código copiado. Envíalo a la persona con quien quieres conectarte.',
      codeInvalidTitle: 'Código inválido',
      codeInvalidMsg: 'Código no encontrado o expirado. Pide un nuevo código.',
      codeUsedTitle: 'Código ya usado',
      codeUsedMsg: 'Este código ya fue utilizado. Pide un nuevo código.',
      ownCodeTitle: 'Error',
      ownCodeMsg: 'No puedes usar tu propio código de invitación.',
      alreadyConnectedTitle: 'Ya conectados',
      alreadyConnectedMsg: (name: string) => `Ya tienes una conexión con ${name}.`,
      rejectTitle: 'Rechazar solicitud',
      rejectMsg: (name: string) => `¿Rechazar conexión de ${name}?`,
      rejectBtn: 'Rechazar',
      disconnectTitle: 'Desconectar',
      disconnectMsg: (name: string) => `¿Terminar la conexión con ${name}?\n\nTodas las listas compartidas entre ustedes (en ambos sentidos) dejarán de aparecer para los dos. Cada uno conserva las listas que creó.`,
      disconnectBtn: 'Desconectar',
      disconnectCleanupError: 'No se pudo revocar el acceso a las listas ahora. Revisa tu conexión e intenta de nuevo — la conexión se mantuvo.',
      errorGenerate: 'No se pudo generar el código. Intenta de nuevo.',
      errorConnect: 'No se pudo enviar la solicitud. Intenta de nuevo.',
      errorAccept: 'No se pudo aceptar. Intenta de nuevo.',
      comingSoon: 'Disponible pronto.',
      authErrorMsg: 'Error de autenticación. Reinicia la app.',
      noDisplayNameMsg: 'Necesitas definir un nombre antes de generar un código. Ve a Configuración → Compartir.',
      modalTitle: 'Compartir con',
      modalDisabled: 'El compartido está desactivado.\nActívalo en Configuración → Compartir.',
      modalNoConnection: 'Sin conexión activa.\nAgrega un contacto en Configuración → Compartir.',
      modalShared: 'Compartido',
      modalClose: 'Cerrar',
      confirmShareTitle: 'Compartir lista',
      confirmShareMsg: (name: string, list: string) => `¿Compartir "${list}" con ${name}?\n\n${name} podrá ver y editar todos los artículos (pero no eliminar la lista).`,
      confirmUnshareTitle: 'Dejar de compartir',
      confirmUnshareMsg: (name: string) => `¿Dejar de compartir esta lista con ${name}?\n\nLa lista desaparecerá del dispositivo de ${name} de inmediato.`,
      partnerUnavailableTitle: 'No disponible',
      partnerUnavailableMsg: (name: string) => `${name} desactivó la compartición y no puede recibir listas ahora. Pídele que la reactive en Configuración → Compartir.`,
      codeEmptyMsg: 'Escribe primero el código de invitación.',
      connectedOn: (date: string) => `conectado el ${date}`,
    },
    search: {
      title: 'Búsqueda',
      searchBtn: 'Buscar',
      placeholder: 'Buscar eventos, listas...',
      dateDetected: 'Fecha detectada:',
      goToDate: 'Ir a esta fecha',
      events: 'COMPROMISOS',
      lists: 'LISTAS',
      noResults: 'Sin resultados para',
      typeToSearch: 'Escribe al menos 2 caracteres para buscar.',
      subtitle: 'Escribe el nombre, etiqueta o fecha',
      noResultsFound: 'Sin resultados encontrados',
      resultsCount: (n: number) => `${n} resultado${n !== 1 ? 's' : ''} encontrado${n !== 1 ? 's' : ''}`,
      sectionEvents: '📅 Eventos y Pendientes',
      sectionLists: '📝 Listas',
      pendingLabel: 'Pendiente',
      listCompleted: 'Finalizada',
      listOpen: 'Abierta',
      tipHint: '💡 Consejo: ¡Escribe una fecha (ej: 25/12/2025) para ir directamente a ese día!',
    },
    alerts: {
      deleteEvent: 'Eliminar evento',
      deleteEventMsg: (title: string) => `¿Eliminar "${title}"? Esta acción no se puede deshacer.`,
      unlinkList: 'Desvincular lista',
      unlinkListMsg: '¿Eliminar el vínculo con esta lista?',
      unlinkListBtn: 'Desvincular',
      reopenEvent: 'Reabrir evento',
      reopenEventMsg: 'Este evento está en el pasado. ¿Qué deseas hacer?',
      moveToPending: 'Mover a Pendientes',
      reschedule: 'Reprogramar',
      linkedListPending: 'Lista pendiente',
      linkedListPendingMsg: 'Completa la lista vinculada antes de completar este evento.',
      exitShare: 'Salir del compartido',
      exitShareMsg: '¿Eliminar este evento de tu vista? El dueño conserva el elemento.',
      exitShareBtn: 'Salir',
      exitShareList: 'Salir del compartido',
      exitShareListMsg: '¿Eliminar esta lista de tu vista? El dueño conserva el elemento.',
      removeItem: 'Eliminar artículo',
      removeItemMsg: '¿Eliminar este artículo?',
      removeItemBtn: 'Eliminar',
      reopenList: 'Reabrir lista',
      reopenListMsg: '¿Reabrir esta lista?',
      finalizeList: 'Finalizar lista',
      finalizeListMsg: '¿Finalizar esta lista?',
      deleteList: 'Eliminar lista',
      deleteListMsg: (name: string) => `¿Eliminar "${name}"? Esta acción no se puede deshacer.`,
      archiveList: 'Archivar lista',
      archiveListMsg: (name: string) => `¿Archivar "${name}"? La lista se eliminará de la pantalla principal y solo estará disponible en Configuración.`,
      archiveListBtn: 'Archivar',
      archiveListSimpleMsg: (name: string) => `¿Archivar "${name}"?`,
      unlinkSimple: 'Desvincular',
      unlinkSimpleMsg: '¿Eliminar el vínculo?',
      deleteWarning: '¡Atención!',
      deleteWarningMsg: 'Los datos seleccionados serán eliminados permanentemente. Esta acción no se puede deshacer.',
      deleteWarningBtn: 'Continuar',
      deleteSure: '¿Estás seguro?',
      deleteSureBtn: 'Borrar',
      deleteArchivedList: 'Eliminar lista archivada',
      deleteArchivedListMsg: (name: string) => `¿Eliminar "${name}" permanentemente?`,
      confirm: 'Confirmar',
      postponeEvent: 'Aplazar compromiso',
      postponeEventMsg: '¿Mover este compromiso a Pendientes?',
      postponeEventBtn: 'Aplazar',
      // Rutinas
      deleteRoutineTitle: 'Eliminar rutina',
      deleteRoutineMsg: (title: string) => `¿Eliminar la rutina "${title}" completa?\n\nTodo el historial de ocurrencias será borrado. Esta acción no se puede deshacer.`,
      deleteRoutineConfirmTitle: 'Confirmar eliminación',
      deleteRoutineConfirmBtn: 'Eliminar de todas formas',
      suspendRoutineTitle: 'Suspender rutina',
      suspendRoutineMsg: 'La rutina será suspendida. Hoy se completará automáticamente, y los días futuros quedarán suspendidos hasta que reanudes.',
      suspendRoutineBtn: 'Suspender',
      routineLinkedListTitle: 'Lista pendiente',
      routineLinkedListMsg: 'Completa la lista vinculada antes de completar esta rutina.',
      unlinkRoutineList: 'Desvincular lista',
      unlinkRoutineListMsg: '¿Eliminar el vínculo con esta lista?',
      reopenRoutineTitle: 'Reabrir ocurrencia',
      reopenRoutineMsg: '¿Marcar esta ocurrencia como no completada?',
      cantDeleteSharedList: 'Sin permiso',
      cantDeleteSharedListMsg: 'No puedes eliminar una lista que se compartió contigo. Puedes eliminar artículos, pero para quitar la lista completa usa el botón Salir.',
      listNameTaken: 'Nombre ya usado',
      listNameTakenMsg: 'No puedes crear la misma lista el mismo día. Elige un nombre diferente o edita la lista existente.',
      itemExists: 'Artículo ya en la lista',
      itemExistsMsg: (name: string) => `"${name}" ya está en la lista. ¿Agregarlo de todos modos?`,
      itemExistsAdd: 'Agregar',
    },
    toast: {
      eventCompleted: '¡Compromiso completado!',
      pendingCompleted: '¡Tarea completada!',
      listCompleted: '¡Lista finalizada!',
      listArchived: 'Lista archivada',
      linked: 'Lista vinculada',
      unlinked: 'Vínculo eliminado',
      shareEnabled: 'Compartición activada',
      shareDisabled: 'Compartición desactivada',
      undo: 'Deshacer',
      allListItemsDone: '¡Todos los artículos marcados!',
      syncError: 'Error al sincronizar — revisa tu conexión',
      listNoLongerShared: 'Esta lista ya no está compartida contigo',
      reshareHint: (n: number) => `Tenías ${n} lista${n !== 1 ? 's' : ''} compartida${n !== 1 ? 's' : ''}. Compártelas de nuevo con el botón Compartir.`,
    },
    onboarding: {
      // Paso 1 — Idioma + Tema
      welcomeSub: '¡Bienvenido! / Welcome! / Bem-vindo!',
      languageLabel: 'Elige tu idioma:',
      themeLabel: 'Elige tu tema:',
      themeDark: 'Oscuro',
      themeLight: 'Claro',
      themeAuto: 'Automático',
      themeAutoHint: 'Sigue la configuración del sistema',
      continueBtn: 'Continuar',
      // Paso 2 — Google Sign-In
      googleTitle: 'Conecta tu cuenta',
      googleDesc: 'Inicia sesión con tu cuenta de Google para habilitar el compartido de listas en tiempo real.\n\nTu nombre se completará automáticamente.',
      googleSignInBtn: 'Iniciar sesión con Google',
      googleSkipBtn: 'Omitir por ahora',
      googleSkipWarning: 'Sin cuenta de Google, el compartido de listas quedará desactivado.',
      googleErrorMsg: 'No pudimos conectar con tu cuenta de Google ahora. Verifica tu conexión a internet e intenta de nuevo.',
      // Paso 2b — Perfil manual
      manualTitle: 'Sobre ti',
      manualDesc: 'Completa tu información para personalizar la app.',
      manualNameLabel: 'Tu nombre o apodo',
      manualNamePlaceholder: 'Ej: Juan, Ju...',
      manualLimitationNote: 'El compartido de listas requiere cuenta de Google.',
      // Paso 3 — Compartición
      sharingTitle: 'Compartición',
      sharingDesc: 'Comparte listas en tiempo real con otras personas.\nLas actualizaciones aparecen instantáneamente para todos los involucrados.',
      sharingEnableBtn: 'Activar compartición',
      sharingSkipBtn: 'Ahora no',
      sharingHint: 'Puedes activarlo después en Configuración.',
      // Paso 4 — Backup
      backupTitle: 'Copia de seguridad',
      backupDesc: 'Elige cómo se protegerán tus datos.',
      backupModeLabel: 'Frecuencia:',
      backupModeAuto: 'Automático',
      backupModeAutoDesc: 'Guarda en cada cambio',
      backupModeManual: 'Manual',
      backupModeManualDesc: 'Tú decides cuándo guardar',
      backupLocationLabel: 'Destino:',
      backupLocationLocal: 'Local',
      backupLocationLocalDesc: 'Archivo en el dispositivo',
      backupLocationCloud: 'Nube',
      backupLocationCloudDesc: 'Guardado en tu cuenta de Google',
      backupCloudDisabledHint: 'Requiere cuenta de Google',
      backupContinueBtn: 'Continuar',
      // Paso 5 — Hidratación
      waterTitle: 'Contador de Hidratación',
      waterDesc: 'Haz seguimiento de tu meta diaria de agua y recibe recordatorios durante el día.\n\nCuando está activo, aparece en la pantalla Hoy con una botella animada.',
      waterEnableBtn: 'Activar Contador',
      waterSkipBtn: 'Omitir',
      waterHint: 'Puedes activarlo después en Configuración.',
      // Paso 6 — Términos de uso
      termsTitle: 'Términos de Uso',
      termsSubtitle: 'Lee con atención antes de usar supLista.',
      termsScrollHint: 'Desplázate hasta el final para habilitar el botón de aceptación.',
      termsAcceptBtn: 'He leído y acepto los Términos de Uso',
    },
  },
} as const;

type Translations = typeof translations.pt;

interface LanguageContextValue {
  lang: LangType;
  setLanguage: (l: LangType) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'pt',
  setLanguage: () => {},
  t: translations.pt,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangType>('pt');

  useEffect(() => {
    loadSettings().then(s => {
      if (s.language) setLangState(s.language as LangType);
    });
  }, []);

  const setLanguage = (l: LangType) => {
    setLangState(l);
    saveSettings({ language: l } as any);
  };

  const t = translations[lang] as Translations;

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
